### PR TITLE
Update recipes to work with latest master branches

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by lewishanly** [comment]
Thank you these and all good.
Can you add a new PR for the commit for '@kraj
u-boot: Fix patch to apply on top of 2020.10 release' ? and remove the commit on this PR.
Once updated we will merge this PR.

**Comment by kevinscully100** [comment]
> 
> 
> Thank you these and all good.
> Can you add a new PR for the commit for '@kraj
> u-boot: Fix patch to apply on top of 2020.10 release' ? and remove the commit on this PR.
> Once updated we will merge this PR.

@lewishanly I assume that this request to amend this PR #14 is addressed to @kraj ? and that it is commit acd122a8344e31208129015eef49f22d1e898622 (which just happens to have the same commit message as the title of this PR) that you want removed from this PR and resubmitted as a separate PR? 
Hope I'm not adding confusion where there is none.

**Comment by kraj** [comment]
well my bad is that I fixed u-boot and then kept on fixing builds with latest master and did not realize that I kept updating same branch as proposed for u-boot pull. So I have separated the u-boot away from this pull and rest of meta-data updates are here.

**Review by lhanlyu — APPROVED** [review]
All these changes are required.

**Review by lhanlyu — APPROVED** [review]

**Pull request merged**
